### ISSUE TITLE
Use `return` and `fail`

### ISSUE THREAD

**Issue by smondet** [dbuenzli/rresult#2]
It would be more “standard” to use the names `return` and `fail` rather than `ret` and `error`.

PS:
I've been playing with the same thing for a while now:
http://seb.mondet.org/software/pvem/index.html
http://seb.mondet.org/software/pvem_lwt_unix/index.html

**Comment by rgrinberg** [comment]
+1 for `return` at least. It's the common name in many module signatures.

**Comment by dbuenzli** [comment]
I added undocumented functions `R.{return,fail}` for compatibilty in module signatures. They are undocumented because I don't think they are good names.
- `fail` is too reminiscent of exceptions (`lwt`'s, `failwith`, etc.) for me. Besides `R.error` also fits the  name of the corresponding case and many other combinators of the module: `R.get_error`, `R.reword_error`, `R.ignore_error`,  `R.ignore_errork` so I don't see the point of having a different name to construct it, that's one less name mapping you need in your brain.  
- I think people should use `R.ret` which is sufficently clear and allows much compacter `let`s (and `ret` is also used, e.g. in `Cmdliner`). I know many people don't care and tend to write horrible and unreadable long winded functions, with unnamed inlined functions/values and other interleaved sequencing operators. But the style I promote is that functions should be sequences of (as much as possible one-liner) `let` bindings, followed by a single expression. Having short combinators makes it easier to achieve that goal.

**Comment by rgrinberg** [comment]
FWIW I don't think `return` is such a great name at all but it's basically ubiquitous and instantly recognizable by anyone who is familiar with monads.

**Comment by dbuenzli** [comment]
Yeah maybe I should even switch to `R.ok` to be fully consistant.

**Comment by dbuenzli** [comment]
Btw. I don't think recognizing the fact there is a monad is useful in anyway. I think that every monad should call its operators with names that make sense to their domain of application.

**Comment by dbuenzli** [comment]
This is in general what I dislike with type classes, names may not be very relevant to the problem domain. E.g. Cmdliner's `Term.pure` would benefit of being called `Term.const` IMHO.

**Comment by smondet** [comment]
I like `{ok, error}` for the domain-specific API together with `{return, fail}` for being compatible the standard-monad module-type (it's useful sometimes to write code against "any monad" using functors or 1st-class modules).

**Comment by dbuenzli** [comment]
> I like {ok, error} for the domain-specific API together with {return, fail}

So it is now. Thanks for the feedback .
