### ISSUE TITLE
Toplevel support doesn't work

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/rresult#5]
No idea what is going on. I tried to implement the scheme mentioned here (https://github.com/dbuenzli/gg/issues/1), i.e. `#require`ing `result.top` installs printers and opens the namespacing module, which as we discussed with @whitequark in the linked issue is a better scheme than automatically doing so on `#require "result"`

Using this [META](https://github.com/dbuenzli/result/blob/5524972bb80e8a67424bc5aa1706a8b875d6fe51/pkg/META#L10-L19) and [this](https://github.com/dbuenzli/result/blob/5524972bb80e8a67424bc5aa1706a8b875d6fe51/src/result_top.ml) loading code results in: 

```
#require "result.top";;
/Users/dbuenzli/.opam/doc/lib/ocaml/compiler-libs: added to search path
/Users/dbuenzli/.opam/doc/lib/ocaml/compiler-libs/ocamlcommon.cma: loaded
/Users/dbuenzli/.opam/doc/lib/ocaml/compiler-libs/ocamlbytecomp.cma: loaded
/Users/dbuenzli/.opam/doc/lib/ocaml/compiler-libs/ocamltoplevel.cma: loaded
/Users/dbuenzli/.opam/doc/lib/result: added to search path
/Users/dbuenzli/.opam/doc/lib/result/result.cma: loaded
/Users/dbuenzli/.opam/doc/lib/result/result_top.cma: loaded
Exception:
Typetexp.Error
 ({Location.loc_start =
    {Lexing.pos_fname = ""; pos_lnum = 1; pos_bol = 0; pos_cnum = 5};
   loc_end =
    {Lexing.pos_fname = ""; pos_lnum = 1; pos_bol = 0; pos_cnum = 17};
   loc_ghost = false},
 <abstr>, Typetexp.Unbound_module (Longident.Lident "Result_infix")).
```

However all the objects are here and visible as it should be:

```
> ls /Users/dbuenzli/.opam/doc/lib/result/
META            result.cmx      result_infix.cmx
opam.config     result.cmxa     result_infix.mli
result.a        result.cmxs     result_top.a
result.cma      result.mli      result_top.cma
result.cmi      result_infix.cmi    result_top.cmxa
result.cmti     result_infix.cmti   result_top.cmxs
```

and `result.cma` has the unit `Result_infix`:

```
> ocamlobjinfo result.cma
[...]
Unit name: Result_infix
[...]
```

Any `ocamlfind` expert has an idea ? Can be tried by 

```
opam pin add resultv http://erratique.ch/repos/resultv.git
```

**Comment by dbuenzli** [comment]
N.B. package renamed to resultv but issue persists. Is there some kind of race in `ocamlfind` or am I doing something stupidly wrong ?

**Comment by whitequark** [comment]
Why did you rename it?.. I liked `result` much better.

Regarding the issue. Hahahaha

What you're hitting here is toplevel expunging. Toplevel is linked with a bunch of stuff from compiler-libs which includes global state. To avoid polluting user's namespace with module names such as `Config`, these modules are removed from toplevel's symbol table using the `expunge` script. If you load `compiler-libs.toplevel`, a _second_ instance of all those modules is loaded and initialized. This includes, say, `Location`, leading to the fact that you can't actually catch a parser error raised by your `exec` function; `with Location.Error _ ->` clause will be silently ignored ([PR6704](http://caml.inria.fr/mantis/view.php?id=6704)). However, `Toploop` and `Topdirs`, for obvious reasons, are not expunged. I believe what happens here is when you load `ocamltoplevel.cma`, the dynamic linker links it to the _existing_ instance of `Toploop`, but it _also_ runs the initialization code from `ocamltoplevel.cma` anew; thus the state is reset.

This can be evident in this log:

```
# module type E = sig end;;
module type E = sig  end
# Hashtbl.length Toploop.directive_table;;
- : int = 35
# (Obj.magic (Hashtbl.find Toploop.directive_table "quit") : int);;
- : int = 70222215889712
# (Obj.magic (module Toploop : E) : int);;
- : int = 3258948
# #require "compiler-libs.toplevel";;
/home/whitequark/.opam/4.02.1/lib/ocaml/compiler-libs: added to search path
/home/whitequark/.opam/4.02.1/lib/ocaml/compiler-libs/ocamlcommon.cma: loaded
/home/whitequark/.opam/4.02.1/lib/ocaml/compiler-libs/ocamlbytecomp.cma: loaded
/home/whitequark/.opam/4.02.1/lib/ocaml/compiler-libs/ocamltoplevel.cma: loaded
# Hashtbl.length Toploop.directive_table;;
- : int = 29
# (Obj.magic (Hashtbl.find Toploop.directive_table "quit") : int);;
- : int = 70222217512508
# (Obj.magic (module Toploop : E) : int);;
- : int = 3258948
```

As you can see the directive table is _cleared_; there is no code anywhere in the toplevel that removes directives, however there is code to create the table from scratch. The `#quit` directive is also reinitialized (which again only happens when `Topdirs` is initializing) while the module itself stays the same. This makes me even further convinced that toplevel expunging is a horrible idea.

The solution, of course, is simply to remove `compiler-libs.toplevel` from the `requires` list.

**Comment by dbuenzli** [comment]
> Why did you rename it?.. I liked result much better.

So did I but if the result type gets into `Pervasives` the compatibility package will likely use `Result` and we could imagine the stdlib defining such a module in the future (one can dream...). See https://github.com/ocaml/ocaml/pull/147

> Regarding the issue. Hahahaha

Hum, well... thanks for the explanation, the proposed fix works.
